/**
 * Unicode primitives shared by the homoglyph attack and the shield's sanitizer.
 *
 * Attack and defense deliberately live in one module: a confusable the attacker
 * can use but the defender cannot see is a bug, and keeping the tables together
 * makes that class of drift impossible.
 */
import { UTS39_CONFUSABLES } from "./confusables-data.js";

/**
 * Confusable single-script characters that render as Latin capitals in almost
 * every font. This is the real Unicode UTS #39 confusables set (not a
 * hand-picked subset): every source codepoint in `confusables.txt` whose
 * confusable chain resolves to a plain ASCII Latin letter, i.e. every
 * character in the authoritative data an attacker could substitute into a
 * ticker symbol while still rendering as that letter to a human reader.
 * 1310 entries, generated by `scripts/generate-confusables.mjs` from
 * https://www.unicode.org/Public/security/latest/confusables.txt \u2014 see
 * `confusables-data.ts` for provenance and regeneration instructions.
 *
 * Keys are the deceptive codepoints; values are the Latin letter they mimic.
 */
export const CONFUSABLES: Readonly<Record<string, string>> = UTS39_CONFUSABLES;

/** Reverse map: Latin letter -> deceptive codepoints that mimic it. */
export const LATIN_TO_CONFUSABLES: Readonly<Record<string, string[]>> = Object.freeze(
  Object.entries(CONFUSABLES).reduce<Record<string, string[]>>((acc, [deceptive, latin]) => {
    (acc[latin] ??= []).push(deceptive);
    return acc;
  }, {}),
);

/**
 * Characters with no visible width. Carriers for hidden-text attacks: invisible
 * to a human reviewing a headline, fully tokenized by the model.
 */
export const INVISIBLE_CHARS: readonly string[] = Object.freeze([
  "\u200B", // zero width space
  "\u200C", // zero width non-joiner
  "\u200D", // zero width joiner
  "\u2060", // word joiner
  "\uFEFF", // zero width no-break space
  "\u00AD", // soft hyphen
  "\u180E", // mongolian vowel separator
]);

/**
 * Bidirectional control characters. These reorder rendered text without
 * changing the logical byte order the model reads — so a human and the model
 * can see genuinely different strings.
 */
export const BIDI_CHARS: readonly string[] = Object.freeze([
  "\u202A", "\u202B", "\u202C", "\u202D", "\u202E",
  "\u2066", "\u2067", "\u2068", "\u2069",
]);

const INVISIBLE_RE = new RegExp(`[${INVISIBLE_CHARS.join("")}]`, "gu");
const BIDI_RE = new RegExp(`[${BIDI_CHARS.join("")}]`, "gu");

/** True when the string contains any zero-width or bidi control character. */
export function hasInvisibleChars(s: string): boolean {
  INVISIBLE_RE.lastIndex = 0;
  BIDI_RE.lastIndex = 0;
  return INVISIBLE_RE.test(s) || BIDI_RE.test(s);
}

/** Strip every zero-width and bidi control character. */
export function stripInvisible(s: string): string {
  return s.replace(INVISIBLE_RE, "").replace(BIDI_RE, "");
}

/** Every confusable codepoint found in the string, with its Latin lookalike. */
export function findConfusables(s: string): Array<{ char: string; mimics: string; index: number }> {
  const found: Array<{ char: string; mimics: string; index: number }> = [];
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (ch === undefined) continue;
    const mimics = CONFUSABLES[ch];
    if (mimics !== undefined) found.push({ char: ch, mimics, index: i });
  }
  return found;
}

/** Fold confusables to their Latin lookalikes, then NFKC-normalize. */
export function skeleton(s: string): string {
  let out = "";
  for (const ch of s) out += CONFUSABLES[ch] ?? ch;
  return out.normalize("NFKC");
}

/**
 * True when two strings render alike but differ in bytes — the signature of a
 * homoglyph attack. Identical strings are not confusable, only deceptive ones.
 */
export function isConfusablyEqual(a: string, b: string): boolean {
  return a !== b && skeleton(a).toUpperCase() === skeleton(b).toUpperCase();
}
